server:
  port: ${SERVER_PORT:8082}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/order}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      username: ${CONFIG_SERVER_USERNAME:root}
      password: ${CONFIG_SERVER_PASSWORD:root}
  application:
    name: order-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import:
      optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  # Sleuth and Zipkin Configuration for Spring Boot 2.7.x
  sleuth:
    sampler:
      probability: 1.0  # Sample 100% for testing
  zipkin:
    base-url: http://localhost:9411
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,httptrace

# Logging pattern to include trace IDs
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.cloud.sleuth: DEBUG  # Enable tracing debug logs
