server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher