server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erik-ggg/microservices-infrastructure
#  security:
#    user:
#      name: root
#      password: s3cr3t
