server:
  port: ${SERVER_PORT:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URI:https://github.com/erik-ggg/micros-config-repo}
          clone-on-start: true
          default-label: ${CONFIG_SERVER_GIT_LABEL:main}
