server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erik-ggg/microservices-infrastructure.git
          clone-on-start: true
  security:
    user:
      name: root
      password: root

